### ISSUE TITLE
Chromium revision is not downloaded

### ISSUE THREAD

**Issue by PawanWagh** [Kikobeats/aws-lambda-chrome#10]
This is what i get when executing the lambda. But, this works on local machine using lambda-local package.
```
{
  "errorMessage": "Chromium revision is not downloaded. Run \"npm install\" or \"yarn install\"",
  "errorType": "Error",
  "stackTrace": [
    "assert (/var/task/node_modules/puppeteer/lib/helper.js:282:11)",
    "Function.launch (/var/task/node_modules/puppeteer/lib/Launcher.js:106:7)",
    "<anonymous>"
  ]
}
```

**Comment by Kikobeats** [comment]
In your production puppeteer is trying to donwload chrome; the thing that you need to do is use this package that contains binary chrome instead of download it.
