### ISSUE TITLE
Few Questions

### ISSUE THREAD

**Issue by j** [Kikobeats/aws-lambda-chrome#11]
I'm debating over hosting a snapshot service on Lambda or Now.sh.  I have questions regarding the use of this repository.

1. How many concurrent requests can this handle?
2. What happens when Chrome crashes?
3. What is the most solid configuration/usage you've found with the use of Chrome & Lambda?
4. Sites like "https://browserless.io" claim that it's best to create a browser each time you need a fresh instance to prevent issues, however doing that with this library takes roughly 7-11 seconds for a 540x720 screenshot... how do we speed this up?

I want to try to avoid crashes at all cost as well as have something that scales well.

**Comment by Kikobeats** [comment]
You are asking for things non related with this project.

I recommend you read about how AWS Lambda scales and also check the puppeteer doc.

In my experience, it works fine.

**Comment by j** [comment]
I suppose that I was trying to ask someone who has experienced Lambda + Chrome in a production environment since you seemed to be knowledgeable and every resource out there doesn't sell me on the consistency.

Thanks for your work.

You should check out https://github.com/alixaxel/chrome-aws-lambda
