### ISSUE TITLE
Unzipped size must be smaller than 262144000 bytes

### ISSUE THREAD

**Issue by tomgallagher** [Kikobeats/aws-lambda-chrome#5]
I'm trying to get this package working on Lambda.

Lambda now supports Node 8.1.0 so that's made it easier for me.

https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/

So I set the runtime on my machine to Node 8.1.0, also the runtime on Lambda.

Following your instructions to the letter, I think.

```
npm install puppeteer browserless --save
npm install @browserless/aws-lambda-chrome --save
```

Create the two files, then zip up my node modules directory, the js files and package.json.

On upload, I get the error message, partly I guess because I'm trying to upload two versions of Chromium, yours and Puppeteer's.

What am I doing wrong?

**Comment by tomgallagher** [comment]
OK, so I've managed to download Puppeteer without Chromium. Doing these things:

In the same level as package.json, create a .npmrc file.
In that file, paste in this:

`puppeteer_skip_chromium_download=true
`

Then you should see a message

**INFO** Skipping Chromium download. "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" was set in npm config.

The size is, as you suggested, greatly decreased.

However, on testing the function, which is very basic, I get this error messsage:

"EACCES: permission denied, open '/var/task/node_modules/proxy-from-env/index.js"

And the stack trace is pointing to:

/var/task/node_modules/puppeteer/lib/BrowserFetcher.js:28:24

which is:

`const getProxyForUrl = require('proxy-from-env').getProxyForUrl;`

Do I need to add some other flag to the browserless launch?

Thanks

**Comment by Kikobeats** [comment]
hmm `EACCES` is related with permissions, not sure if is s related with this

**Comment by tomgallagher** [comment]
OK, here's my lambda function code, just in case I've made an error.

```
exports.handler = async (event) => {
    const browserInstance = require('./init-browser');
    const browserless = await browserInstance();
    const browser = await browserless.browser;
    const page = await browserless.page();
}

```
init.browser.js just a copy of the example.
