### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by sean-hill** [Kikobeats/aws-lambda-chrome#7]
Hey! Thanks for this great plugin. I'm facing an issue where puppeteer fails to launch the `headless_shell` binary.

Here's my code snippet (using the serverless framework):

```js
const puppeteer = require('puppeteer')
const getChromePath = require('@browserless/aws-lambda-chrome')({
  path: '/tmp'
})

module.exports.handler = async (event, context) => {
  const browser = await puppeteer.launch({
    executablePath: await getChromePath()
  })

  const page = await browser.newPage()
  await page.goto('https://example.com')
  console.log(await page.title())

  await browser.close()
}
```

The error I get is:

```sh
  Error --------------------------------------------------

  Failed to launch chrome!
/tmp/headless_shell: /tmp/headless_shell: cannot execute binary file


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

Any suggestions?

**Comment by Kikobeats** [comment]
actually no idea, looks like your env is not an AWS Lambda, could be possible?

**Comment by sean-hill** [comment]
Yeah @Kikobeats I'm just testing locally on my computer.

**Comment by sean-hill** [comment]
@Kikobeats understood, thanks! Just a quick question, I installed puppeteer without installing the local chromium so that I could use this package. What development workflow do you have when developing locally and can't use the binary? AKA do you install puppeteer fully, and then remove it before packaging for Lambda?

**Comment by Kikobeats** [comment]
In my case, becase I'm using [up](up.docs.apex.sh) for deploying, It supports create a `.upignore` of files to be ignored, so I basically I added the local puppeteer there

I created a package for generate the file:
https://github.com/Kikobeats/untracked
