### ISSUE TITLE
Build script is broke

### ISSUE THREAD

**Issue by jfizz** [Kikobeats/aws-lambda-chrome#8]
I am trying to build my own binary. I launched the recommended instance type, downloaded the build script then executed it. The script errors out:
```
Error: client not configured; see 'gclient config'
```
I was able to resolve that issue using advice found here https://bugs.chromium.org/p/v8/issues/detail?id=3787.
```
gclient config https://chromium.googlesource.com/v8/v8
```
However, running the build script again led to:
```
gn.py: Could not find checkout in any parent of the current path.
This must be run inside a checkout.
```
which is caused by ```gn gen out/Headless```.

Have you been able to run the build script lately?

**Comment by Kikobeats** [comment]
Hey,

Thanks for the comment. Actually, we are not maintained the build script present in this repository, so I decided removed it.

Instead, I added a list of the good repository with instructions for compile your own version. Check the FAQ right now: https://github.com/Kikobeats/aws-lambda-chrome#faq
